name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/whiteout-project/bot || true
          git fetch upstream

      - name: Smart Merge (Exclude Workflows)
        run: |
          git checkout main
          git merge --no-edit --no-commit upstream/main || true
          git reset -- .github/workflows/
          git commit -m "Sync upstream [skip ci]" || echo "No changes to commit"
          git diff --exit-code || git push origin main
