name: Sync Fork (Full Sync)

on:
  schedule:
    - cron: '0 0 * * 1'  # Weekly at midnight Monday
  workflow_dispatch:     # Manual trigger option

jobs:
  sync:
    runs-on: ubuntu-latest
    # Grant all necessary permissions
    permissions:
      contents: write    # For code changes
      actions: write     # For workflow modifications
      workflows: write   # Explicit workflow permission

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add upstream
        run: |
          git remote add upstream https://github.com/whiteout-project/bot || git remote set-url upstream https://github.com/whiteout-project/bot
          git fetch upstream

      - name: Merge changes
        run: |
          git checkout main
          git merge --no-edit upstream/main || {
            echo "::error::Merge conflict detected"
            git merge --abort
            exit 1
          }

      - name: Push changes
        run: |
          git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" main
